### ISSUE TITLE
Add seq-head, seq-tail, seq-last, seq-butlast

### ISSUE THREAD

**Issue by Fuco1** [NicolasPetton/seq.el#9]
Some helpers as analogues for `car`, `cdr`, `last` and `butlast` would be helpful.  These can be achieved with take and drop but having to specify the number is a bit annoying.

I'm defining a lot of these in Elsa (https://github.com/emacs-elsa/Elsa/blob/master/elsa-reader.el#L261) to work generically with lists and forms and I figured I could extend `seq` to support my types, but I miss these simple helpers.

**Comment by ghost** [comment]
Matus Goljer <notifications@github.com> writes:

> Some helpers as analogues for car, cdr, last and butlast would be
> helpful. These can be achieved with take and drop but having to
> specify the number is a bit annoying.

Could be nice but would of course not be compatible with all kinds of
seqs - e.g. "last" would not (always) make sense for streams.

Since seq is part of Emacs now, I really would prefer to discuss this in
emacs-dev - or maybe even better you could open a request as Emacs bug
report?

Dunno if Nicolas has still time to care about seq, so you may end up to
have to do it yourself, or I have to do it etc, unless Nicolas doesn't
want us to do it at all.

Michael.

**Comment by NicolasPetton** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Dunno if Nicolas has still time to care about seq,

I focused on other packages lately, but I do care about seq.

> so you may end up to have to do it yourself, or I have to do it etc,
> unless Nicolas doesn't want us to do it at all.

I don't have any issue with contributions :-)

**Comment by NicolasPetton** [comment]
Commit 5a9eba603d in Emacs master introduce `seq-first` and `seq-rest`. `seq-last` and `seq-butlast` could be added too, but I'm waiting a bit for those as they can be more controversial, since they make no sense on streams and would be expensive on lists.
